### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by lgrosales** [jesseemerick/NGeoHash#1]
Hi, do you take PRs? This project is lacking tests.

**Comment by jesseemerick** [comment]
Yeah.  Totally!  Send 'em my way.

**Comment by lgrosales** [comment]
Will do. 
And would you take another PR to make a .net standard version of the library?

**Comment by jesseemerick** [comment]
Yeah -- I'll take whatever you're willing to do.  Thanks!

**Comment by jesseemerick** [comment]
Thanks!
