### ISSUE TITLE
Push new version out to NuGet for NETStandard 2 now please

### ISSUE THREAD

**Issue by Siliconrob** [jesseemerick/NGeoHash#9]

**Comment by jesseemerick** [comment]
Yep.  Unfortunately Leonardo Rosales set up the Nuget feed and he is the sole owner.  I just pinged him this morning to either make me an owner or push it himself.

**Comment by jesseemerick** [comment]
Update:  I have not heard from Leonardo at all.  Currently petitioning Nuget.org to get control of the Nuget feed back.

**Comment by Siliconrob** [comment]
Thanks for updates.

I can add appveyor and travis ci automated tests in another request

**Comment by jesseemerick** [comment]
Update:

Hi,

    

Thank you for contacting NuGet Support.

Our dispute resolution policy is documented here https://docs.microsoft.com/en-us/nuget/policies/dispute-resolution. We encourage you to work with klink to take ownership of the package. If you don’t get a response from him within 30 days, please forward us a copy of the message, and we will give you ownership of the package.

 

Kind regards,

Svetlana

NuGet Team

**Comment by jesseemerick** [comment]
Pushed and listed.  :)
